sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
env:
  NODE_ENV="development"
install:
  - npm install
  - npm install -g angular-cli
script:
  - npm test
